church_name: Immanuel Baptist Church
description:
church_logo_image_path: /uploads/logo.png
church_logo2_image_path: /uploads/logo2.jpg
default_header_image: /uploads/logo2.jpg
phone: 661-725-0479
church_email: info@delanobaptist.org
facebook: 'https://www.facebook.com/profile.php?id=100006405525766'
twitter:
youtube:
address: 2327 Oxford Street
address2:
City: Delano
State: CA
Zip: '93215'
main_blog_image: /uploads/1.jpg
main_sermon_image: /uploads/2.jpg
default_calendar_image: /uploads/3.jpg
services:
  - name: Sunday School
    time_of_service: '10:00 am'
    day: Sunday
  - name: Morning Worship
    time_of_service: '11:00 am'
    day: Sunday
  - name: Evening Worship
    time_of_service: '2:00 pm'
    day: Sunday
  - name: Wednesday Prayer Meeting
    time_of_service: '7:00 pm'
    day: Wednesday
lattitude: '16.7736028'
longitude: '96.1604377'
map_zoom_level: 13
Google_calendar_id: ibc93215@gmail.com